/*
 * Copyright (c) Tile-AI Corporation.
 * Licensed under the MIT License.
 */

/*!
 * \file npu_simt_indirect_load.cc
 * \brief Lower the phase-1 A5 SIMT indirect-load pattern.
 */

#include <tvm/arith/analyzer.h>
#include <tvm/runtime/registry.h>
#include <tvm/tir/expr.h>
#include <tvm/tir/op.h>
#include <tvm/tir/stmt.h>
#include <tvm/tir/stmt_functor.h>
#include <tvm/tir/transform.h>

namespace tvm {
namespace tl {

using namespace tir;

namespace {

constexpr const char *kFeature = "A5 SIMT indirect load phase 1";

struct IndirectLoadPattern {
  const BufferLoadNode *src_load{nullptr};
  const BufferLoadNode *idx_load{nullptr};
  Buffer dst_buffer;
  PrimExpr valid_extent;
};

bool IsSharedScope(const Buffer &buffer) {
  return buffer.scope() == "shared" || buffer.scope() == "shared.dyn";
}

bool SameExpr(const PrimExpr &lhs, const PrimExpr &rhs) {
  return StructuralEqual()(lhs, rhs);
}

PrimExpr MakeRegion(Buffer buffer, PrimExpr offset, int access_mask,
                    PrimExpr extent) {
  Op region_op = Op::Get("tl.region");
  PrimExpr load = BufferLoad(buffer, {offset});
  Array<PrimExpr> args = {load, make_const(DataType::Int(32), access_mask),
                          extent};
  return Call(DataType::Handle(), region_op, args);
}

PrimExpr MatchTailMask(PrimExpr condition, const Var &loop_var) {
  // Accept the two tail forms generated by TileLang today:
  //   if i < valid
  //   if start + i < N
  // Both lower to a per-block valid lane count consumed by the backend mask.
  const auto *lt = condition.as<LTNode>();
  if (!lt) {
    return PrimExpr();
  }
  if (SameExpr(lt->a, loop_var)) {
    return lt->b;
  }

  const auto *add = lt->a.as<AddNode>();
  if (!add) {
    return PrimExpr();
  }
  if (SameExpr(add->a, loop_var)) {
    return lt->b - add->b;
  }
  if (SameExpr(add->b, loop_var)) {
    return lt->b - add->a;
  }
  return PrimExpr();
}

bool MatchStoreBody(const Stmt &stmt, const Var &loop_var,
                    IndirectLoadPattern *pattern) {
  // Phase 1 deliberately matches only the canonical indirect-load store:
  //   O_UB[i] = X[IDX_UB[i]]
  // Other arithmetic around the result should be expressed in later statements.
  const auto *store = stmt.as<BufferStoreNode>();
  if (!store || store->indices.size() != 1U) {
    return false;
  }
  if (!SameExpr(store->indices[0], loop_var)) {
    return false;
  }

  const auto *src_load = store->value.as<BufferLoadNode>();
  if (!src_load || src_load->indices.size() != 1U) {
    return false;
  }
  const auto *idx_load = src_load->indices[0].as<BufferLoadNode>();
  if (!idx_load || idx_load->indices.size() != 1U) {
    return false;
  }
  if (!SameExpr(idx_load->indices[0], loop_var)) {
    return false;
  }

  pattern->src_load = src_load;
  pattern->idx_load = idx_load;
  pattern->dst_buffer = store->buffer;
  return true;
}

class NpuSimtIndirectLoadRewriter : public StmtMutator {
 public:
  Stmt VisitStmt_(const ForNode *op) final {
    if (op->kind != ForKind::kParallel) {
      return StmtMutator::VisitStmt_(op);
    }

    Optional<Stmt> rewritten = TryRewrite(op);
    if (rewritten.defined()) {
      return rewritten.value();
    }
    return StmtMutator::VisitStmt_(op);
  }

 private:
  Optional<Stmt> TryRewrite(const ForNode *op) {
    PrimExpr valid_extent = op->extent;
    Stmt body = op->body;

    // Unsupported T.Parallel forms are left untouched so the regular NPUIR
    // vectorization path can still handle them.
    if (const auto *if_node = op->body.as<IfThenElseNode>()) {
      if (if_node->else_case.defined()) {
        return NullOpt;
      }
      valid_extent = MatchTailMask(if_node->condition, op->loop_var);
      if (!valid_extent.defined()) {
        return NullOpt;
      }
      body = if_node->then_case;
    }

    IndirectLoadPattern pattern;
    if (!MatchStoreBody(body, op->loop_var, &pattern)) {
      return NullOpt;
    }
    pattern.valid_extent = valid_extent;

    if (!CanRewriteBoundary(op, pattern)) {
      return NullOpt;
    }
    return BuildIndirectLoad(op, pattern);
  }

  bool CanRewriteBoundary(const ForNode *op,
                          const IndirectLoadPattern &pattern) {
    // Boundary misses are not errors at this TIR stage. Leave the original
    // loop intact so NpuLoopVectorize can still handle the SIMD path.
    const auto *extent = op->extent.as<IntImmNode>();
    if (!extent || extent->value <= 0 || !is_zero(op->min)) {
      return false;
    }
    if (!pattern.valid_extent.dtype().is_int() &&
        !pattern.valid_extent.dtype().is_uint()) {
      return false;
    }

    if (pattern.src_load->buffer.scope() != "global") {
      return false;
    }
    if (!IsSharedScope(pattern.idx_load->buffer) ||
        !IsSharedScope(pattern.dst_buffer)) {
      return false;
    }

    if (pattern.src_load->buffer->dtype != DataType::Float(32)) {
      return false;
    }
    if (pattern.idx_load->buffer->dtype != DataType::Int(32)) {
      return false;
    }
    return pattern.dst_buffer->dtype == pattern.src_load->buffer->dtype;
  }

  Stmt BuildIndirectLoad(const ForNode *op,
                         const IndirectLoadPattern &pattern) {
    PrimExpr zero = make_zero(op->loop_var.dtype());
    PrimExpr block = op->extent;

    // The replacement is an internal TileLang op. Developer-mode codegen lowers
    // it to the backend-recognized triton_indirect_load call.
    PrimExpr src_region = MakeRegion(pattern.src_load->buffer, zero, 1,
                                     make_const(DataType::Int(32), 1));
    PrimExpr idx_region = MakeRegion(pattern.idx_load->buffer, zero, 1, block);
    PrimExpr dst_region = MakeRegion(pattern.dst_buffer, zero, 2, block);

    Op indirect_load_op = Op::Get("tl.npuir_indirect_load");
    Array<PrimExpr> args = {src_region, idx_region, dst_region,
                            pattern.valid_extent};
    PrimExpr call = Call(DataType::Void(), indirect_load_op, args);
    return Evaluate(call);
  }
};

}  // namespace

using namespace tir::transform;

tvm::transform::Pass NpuSimtIndirectLoad() {
  auto pass_func = [=](PrimFunc f, IRModule m, PassContext ctx) {
    // This pass must run before NpuLoopVectorize, otherwise the canonical
    // T.Parallel form is already converted into the SIMD loop representation.
    auto *new_pf = f.CopyOnWrite();
    new_pf->body = NpuSimtIndirectLoadRewriter()(std::move(new_pf->body));
    return f;
  };
  return CreatePrimFuncPass(pass_func, 0, "tl.NpuSimtIndirectLoad", {});
}

TVM_REGISTER_GLOBAL("tl.transform.NpuSimtIndirectLoad")
    .set_body_typed(NpuSimtIndirectLoad);

}  // namespace tl
}  // namespace tvm
